CREATE TABLE client
( UserNAME VARCHAR(255) NOT NULL,
  UserPassword VARCHAR(255) NOT NULL,
  FNAME VARCHAR(25) NOT NULL,
  LNAME VARCHAR(25) NOT NULL,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  LICENSE_NUMBER VARCHAR(10) NOT NULL,
  EMAIL_ID VARCHAR(30) NOT NULL,
  STREET VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  STATE_NAME VARCHAR(20) NOT NULL,
  ZIPCODE VARCHAR(5) NOT NULL,


  CONSTRAINT client_pk
  PRIMARY KEY (Client_ID),
  UNIQUE KEY UserNAME (UserNAME)
);

CREATE TABLE CAR
( REGISTRATION_NUMBER INT(7) NOT NULL,
  MODEL_NAME VARCHAR(25) NOT NULL,
  MAKE VARCHAR(25) NOT NULL,
  MODEL_YEAR NUMERIC(4) NOT NULL,
  FULLOVERVIEW Longtext DEFAULT NULL,
  COST_PER_DAY INTEGER(11) DEFAULT NULL,
  AVAILABILITY_FLAG CHAR(1) NOT NULL,

   CONSTRAINT CARPK
  PRIMARY KEY (REGISTRATION_NUMBER) REFERENCES RES_DETAILS(RES_ID)


) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;



CREATE TABLE RES_DETAILS
( RES_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  FROM_DT_TIME DATETIME NOT NULL,
  RET_DT_TIME DATETIME NOT NULL,
  AMOUNT NUMERIC(10,2) NOT NULL,

CONSTRAINT RESPK
  PRIMARY KEY (RES_ID),
 UNIQUE INDEX (RES_ID) ,


 CONSTRAINT RES1PK
  FOREIGN KEY (RES_ID) REFERENCES CAR(REGISTRATION_NUMBER)




);












CREATE TABLE BOOKING_DETAILS
( BOOKING_ID CHAR(5) NOT NULL,
  FROM_DT_TIME DATETIME NOT NULL,
  RET_DT_TIME DATETIME NOT NULL,
  AMOUNT NUMERIC(10,2) NOT NULL,
  BOOKING_STATUS CHAR(1) NOT NULL,
  PICKUP_LOC  CHAR(4) NOT NULL,
  DROP_LOC CHAR(4) NOT NULL,
  REG_NUM CHAR(7) NOT NULL,
  DL_NUM CHAR(8) NOT NULL,
  INS_CODE CHAR(4),
  ACT_RET_DT_TIME DATETIME,
  DISCOUNT_CODE CHAR(4),

  CONSTRAINT BOOKINGPK
  PRIMARY KEY (BOOKING_ID),

  CONSTRAINT BOOKINGFK1
  FOREIGN KEY (PICKUP_LOC) REFERENCES LOCATION_DETAILS(LOCATION_ID),

  CONSTRAINT BOOKINGFK2
  FOREIGN KEY (DROP_LOC) REFERENCES LOCATION_DETAILS(LOCATION_ID),

  CONSTRAINT BOOKINGFK3
  FOREIGN KEY (REG_NUM) REFERENCES CAR(REGISTRATION_NUMBER),

  CONSTRAINT BOOKINGFK4
  FOREIGN KEY (DL_NUM) REFERENCES Client(Client_ID),

  CONSTRAINT BOOKINGFK5
  FOREIGN KEY (INS_CODE) REFERENCES RENTAL_CAR_INSURANCE(INSURANCE_CODE),

  CONSTRAINT BOOKINGFK6
  FOREIGN KEY (DISCOUNT_CODE) REFERENCES DISCOUNT_DETAILS(DISCOUNT_CODE)
);
