CREATE TABLE client
( UserNAME VARCHAR(30) NOT NULL,
  UserPassword VARCHAR(30) NOT NULL,
  FNAME VARCHAR(25) NOT NULL,
  LNAME VARCHAR(25) NOT NULL,
  PHONE_NUMBER VARCHAR(10) NOT NULL,
  LICENSE_NUMBER VARCHAR(10) NOT NULL,
  EMAIL_ID VARCHAR(30) NOT NULL,
  STREET VARCHAR(30) NOT NULL,
  CITY VARCHAR(20) NOT NULL,
  STATE_NAME VARCHAR(20) NOT NULL,
  ZIPCODE VARCHAR(5) NOT NULL,


  CONSTRAINT client_pk
  PRIMARY KEY (Client_ID),
  UNIQUE KEY UserNAME (UserNAME)
);




CREATE TABLE RES_DETAILS
( RES_ID INT UNSIGNED NOT NULL AUTO_INCREMENT,
  FROM_DT_TIME DATETIME NOT NULL,
  RET_DT_TIME DATETIME NOT NULL,
  AMOUNT NUMERIC(10,2) NOT NULL,

CONSTRAINT RESPK
  PRIMARY KEY (RES_ID),
 UNIQUE INDEX (RES_ID) ,


 CONSTRAINT RES1PK
  FOREIGN KEY (RES_ID) REFERENCES CAR(REGISTRATION_NUMBER)




);







);
